import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Map from '../components/Map'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Eliste Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>

      <main>
        <Map></Map>
      </main>

      <Footer/>
    </div>
  )
}
