import { Card } from '@material-tailwind/react'
import Head from 'next/head'
import Image from 'next/image'
import Cards from '../components/Cards'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Map from '../components/Map'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Eliste Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.15.0/css/all.css" />
      </Head>

      <Header />

      <main className='min-h-60 m-0 p-0'>
        <section className='relative'>
          <Map></Map>
          <div className='absolute bottom-8 left-8 px-4'>
            <div className="flex gap-2 flex-col lg:flex-row">
              <Cards></Cards>
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  )
}
